_include_yml: orthrus

construction:
  enforce_chronological_splits: True

featurization:
  training_split: train

feat_inference:
  sort_edges_by_time: True

batching:
  intra_graph_batching:
    tgn_last_neighbor:
      assert_causal_neighbors: True

training:
  validation_only: True

evaluation:
  selected_epoch: -1
  node_evaluation:
    use_kmeans: False
